apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-mwtfekkk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-mwtfekkk:fe2f42d02b5f679beb979a595669fbf29059ae97@sha256:70bd38bb4da1d03b441a758782dbbed524efffcb920d3abf7196ed08ed06ffd6
        name: container-image  
